# Generated by Django 4.2 on 2023-04-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.IntegerField(db_column='employeeID', primary_key=True, serialize=False)),
                ('medicare', models.CharField(max_length=12, unique=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=25, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='dateOfBirth', null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('postal', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('citzenship', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facilityid', models.AutoField(db_column='facilityID', primary_key=True, serialize=False)),
                ('facilityname', models.CharField(blank=True, db_column='facilityName', max_length=75, null=True)),
                ('facilitywebaddress', models.CharField(blank=True, db_column='facilityWebAddress', max_length=200, null=True)),
                ('facilitytype', models.CharField(blank=True, db_column='facilityType', max_length=30, null=True)),
                ('facilityphone', models.CharField(blank=True, db_column='facilityPhone', max_length=15, null=True)),
                ('facilityaddress', models.CharField(blank=True, db_column='facilityAddress', max_length=50, null=True)),
                ('facilitypostalcode', models.CharField(blank=True, db_column='facilityPostalCode', max_length=10, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infected',
            fields=[
                ('infectionnumber', models.IntegerField(db_column='infectionNumber', primary_key=True, serialize=False)),
                ('infectiondate', models.DateField(blank=True, db_column='infectionDate', null=True)),
                ('infectiontype', models.CharField(blank=True, db_column='infectionType', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Infected',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occupationid', models.IntegerField(db_column='occupationID', primary_key=True, serialize=False)),
                ('occupationname', models.CharField(blank=True, db_column='occupationName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Occupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postalcode',
            fields=[
                ('postalcode', models.CharField(db_column='postalCode', max_length=30, primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'PostalCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('scheduleid', models.IntegerField(db_column='scheduleID', primary_key=True, serialize=False)),
                ('starttime', models.DateField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateField(blank=True, db_column='endTime', null=True)),
                ('scheduledate', models.DateField(blank=True, db_column='scheduleDate', null=True)),
                ('occupationname', models.CharField(blank=True, db_column='occupationName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccineid', models.IntegerField(db_column='vaccineID', primary_key=True, serialize=False)),
                ('vaccinename', models.CharField(blank=True, db_column='vaccineName', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Vaccine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeerole',
            fields=[
                ('occupationid', models.OneToOneField(db_column='occupationID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.occupation')),
            ],
            options={
                'db_table': 'EmployeeRole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.employee')),
                ('dosenum', models.IntegerField(db_column='doseNum')),
                ('datereceived', models.DateField(blank=True, db_column='dateReceived', null=True)),
            ],
            options={
                'db_table': 'Received',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workat',
            fields=[
                ('employeeid', models.OneToOneField(db_column='employeeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.employee')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WorkAt',
                'managed': False,
            },
        ),
    ]
