# Generated by Django 4.2 on 2023-04-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='received',
            options={},
        ),
    ]
