# Generated by Django 4.2 on 2023-04-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_received_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='facilityid',
            field=models.ForeignKey(blank=True, db_column='facilityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.facility'),
        ),
        migrations.AddField(
            model_name='received',
            name='vaccineid',
            field=models.ForeignKey(blank=True, db_column='vaccineID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vaccine'),
        ),
        migrations.AlterModelTable(
            name='received',
            table=None,
        ),
    ]
